### ISSUE TITLE
the installation should be npm install --save-dev ionic-log-file-appender

### ISSUE THREAD

**Issue by twltony** [SmartMoveSystems/ionicLogFileAppender#1]
Firstly, thanks for this nice plugin. 👍 
in the `Readme.md` Installation should be `npm install --save-dev ionic-log-file-appender`

**Comment by y-a-n-n** [comment]
Hi there! Thanks for the feedback.

I assume you meant ```npm install --save ionic-log-file-appender```. If that's the case, you're correct. I'll make sure to fix that up.

**Comment by y-a-n-n** [comment]
Fixed at 2c8b0082d365b394b395db18a2d93f668bb52457
