### ISSUE TITLE
Providers creation failed in app.module

### ISSUE THREAD

**Issue by ThibertT** [SmartMoveSystems/ionicLogFileAppender#2]
Hello,

I have followed your README, everything is fine at compilation time but when starting the app it seems that the logProviders could not be created : see error below 

Unhandled Promise rejection: Cannot read property 'Ionic' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'Ionic' of undefined
    at setupConfig (vendor.js:22437)
    at _callFactory (vendor.js:11002)
    at _createProviderInstance$1 (vendor.js:10952)
    at initNgModule (vendor.js:10902)
    at new NgModuleRef_ (vendor.js:12145)
    at Object.createNgModuleRef (vendor.js:12135)
    at NgModuleFactory_.create (vendor.js:15569)
    at vendor.js:5721
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (vendor.js:4980) TypeError: Cannot read property 'Ionic' of undefined
    at setupConfig (file:///android_asset/www/build/vendor.js:22437:23)
    at _callFactory (file:///android_asset/www/build/vendor.js:11002:20)
    at _createProviderInstance$1 (file:///android_asset/www/build/vendor.js:10952:26)
    at initNgModule (file:///android_asset/www/build/vendor.js:10902:28)
    at new NgModuleRef_ (file:///android_asset/www/build/vendor.js:12145:9)
    at Object.createNgModuleRef (file:///android_asset/www/build/vendor.js:12135:12)
    at NgModuleFactory_.create (file:///android_asset/www/build/vendor.js:15569:25)
    at file:///android_asset/www/build/vendor.js:5721:78
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:14976)
    at Object.onInvoke (file:///android_asset/www/build/vendor.js:4980:33)

Thank for your help

**Comment by y-a-n-n** [comment]
Hi there! Thanks for the heads up.

I managed to reproduce this problem, and it turned out this was a documentation issue. The fix is to remove ```Platform``` from the ```providers``` array in your app.module. I've update the documentation to reflect this, as well as fixing up a couple other inaccuracies.

Please let me know if this fixes your issue.

**Comment by ThibertT** [comment]
Hi there, thank you for the quick reply :) 

Everything is fine now at runtime ! 

BUT I am not able to find the .log file created... 

I've let the default configuration but "logToConsole: true".  Everything seems to be fine : see console output below : 

[2018-10-18 11:59:35.254] Initialising file logger
[2018-10-18 11:59:35.789] File logger initialised: /logs/log.2018-10-18_11-32-52-339.log
[2018-10-18 11:59:36.674] Something has been done!

But unable to find this file...

**Comment by ThibertT** [comment]
Ok so I found out that the file is created at : file:///storage/emulated/0/Android/data/com.myAppName/files/ which is only root access. 

But when I'am trying to read the files like that : 

```
this.log.log('Something has been done!');   


    this.log.getLogFiles()
          .then((files : Entry[]) => {
            // Do something with the files!
          })
          .catch(err => {
            console.log("TTR log file err : " + err);
            // Oops, there was an error!
          });
```

There is a compilation issue : Cannot find name 'Entry'.
What do I need to import ?

If i just console.log like that : 

```
    this.log.getLogFiles()
          .then((files) => {
            console.log("log file : " + JSON.stringify(files));
            // Do something with the files!
          })
          .catch(err => {
            console.log("log file err : " + err);
            // Oops, there was an error!
          });  
```

The output is not relevant for me (As I was waiting to see my log input) : 

log file : [{"isFile":true,"isDirectory":false,"name":"log.2018-10-18_14-29-48-539.log","fullPath":"/logs/log.2018-10-18_14-29-48-539.log","filesystem":"<FileSystem: files>","nativeURL":"file:///data/user/0/com.myAppName/files/logs/log.2018-10-18_14-29-48-539.log"}]


Could you told me how to get the log file as string or object array or anything relevant to do some actions on that ?

Thank for your help

**Comment by ThibertT** [comment]
In fact I am trying to get the log file in order to send it then by mail

**Comment by y-a-n-n** [comment]
Hi again,

The ```Entry``` class you can import from ```@ionic-native/file```.

You can process entry objects using the Ionic Native File plugin's methods:
https://ionicframework.com/docs/native/file/#readAsText

As for sending the logs: I recommend zipping them using JSZip

https://www.npmjs.com/package/jszip

You can do something like the following:

```typescript
import {Entry, File} from '@ionic-native/file';
import * as JSZip from 'jszip';
...
    const zipFile: JSZip = new JSZip();
    this.log.getLogFiles()
      .then((files: Entry[]) => {
        for (let entry of files) {
          const fullPath = entry.fullPath;
          const path = fullPath.replace(entry.name, '');
          this.file.readAsBinaryString(this.file.dataDirectory + path, entry.name)
            .then(data => {
              zipFile.file(entry.name, data);
            });
        }
      });

```

Any further advice regarding sending the files themselves is really outside the scope of this package, so I'm closing this issue. Good luck!

**Comment by ThibertT** [comment]
I am only using the output of readAsBinaryString to send it by mail, that is working nice !

Thank you for the plugin and your help.
