### ISSUE TITLE
Plugin don't do the rollover on 'fileMaxLines'

### ISSUE THREAD

**Issue by ThibertT** [SmartMoveSystems/ionicLogFileAppender#3]
Hi it's me again :)

I am trying to force the plugin to rollover the file according only to the number of lines.

So here is my plugin config : 

```
 {
        enableMetaLogging: false,
        logToConsole: true,
        logDateFormat: 'yyyy-MM-dd HH:mm:ss.SSS',
        fileDateFormat: 'yyyy-MM-dd_HH-mm-ss-SSS',
        fileMaxLines: 50, // I want one and only log file  
        fileMaxSize: 100000000000,//extreme size in order to rollover only according to fileMaxLines 
        totalLogSize: 500000000000,//extreme size in order to rollover only according to fileMaxLines 
        logDir: 'Logs',
        logPrefix: 'log',
        devMode: false
    }
```

I can see that the size of the log file keeps increasing accordingly to what I log into but I never seen the rollover (my log's file is a lot more than 50 lines... Or is fileMaxLines not the number of lines but the number of call to the log function ? )

Thank for your help !

**Comment by y-a-n-n** [comment]
Hello again,

In the configuration, fileMaxLines refers to the maximum number of log entries (calls to the log function) before rollover. It doesn't count lines any other way. 

If you are trying to rollover based on string length or number of line breaks, you may need to manage this yourself or fork this repo to implement such functionality.

**Comment by ThibertT** [comment]
Hello,

Even if fileMaxLines refers to the number of calls to the log function it doesn't work. 
I have made a test with fileMaxLines = 10 and many log function call. I can see that there is always the same 10 logs in the log file.

**Comment by ThibertT** [comment]
Ok I see, 
this is not really a rollover, the plugin create a new file when number of log function call is over fileMaxLines ? 

Is it possible to erase the logs in the log's file and rewrite in the same file when exceeding fileMaxLines ?

**Comment by y-a-n-n** [comment]
No, that is not possible the way the code is written currently. The plugin is designed to write multiple log files and clean up the oldest ones based on the configuration you choose, not to rewrite a single file. 

If you'd like to dig deeper into what is happening in your particular case, you can set ```enableMetaLogging: true``` as this will print verbose information regarding the behaviour of the logger.
