### ISSUE TITLE
Can't resolve all parameters for LogProvider

### ISSUE THREAD

**Issue by MrWeezle** [SmartMoveSystems/ionicLogFileAppender#5]
I integrated the plugin to my project. But when I am building it, it throws following error message:

`Uncaught Error: Can't resolve all parameters for LogProvider: ([object Object], [object Object], [object Object], ?).
    at syntaxError (vendor.js:108172)
    at CompileMetadataResolver._getDependenciesMetadata (vendor.js:124725)
    at CompileMetadataResolver._getTypeMetadata (vendor.js:124618)
    at CompileMetadataResolver._getInjectableTypeMetadata (vendor.js:124840)
    at CompileMetadataResolver.getProviderMetadata (vendor.js:124849)
    at vendor.js:124787
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver._getProvidersMetadata (vendor.js:124747)
    at CompileMetadataResolver.getNgModuleMetadata (vendor.js:124466)
    at JitCompiler._loadModules (vendor.js:131750)`

I am using Ionic Version 4.12.0.

**Comment by y-a-n-n** [comment]
Hi,

Can you show me how you call the LogProvider constructor in your app.module file? It should look something like this:

```
export function provideLogger(file: File, platform: Platform, datePipe: DatePipe) {
  /**
   * Provider for persistent file logging services
   */
  return new LogProvider(file, platform, datePipe, new LogProviderConfig({/*your config here*/}));
}
```

Based on the error message, it seems like you might not be providing a LogProviderConfig object to the constructor correctly.

**Comment by y-a-n-n** [comment]
Hello again,

I have just released version 2.0.3 which I expect will fix this issue. Note that there are changes to the way the LogProvider should be incorporated into your project; please consult the README for details.

**Comment by ojpeters** [comment]
I am having same issue.
Just added to my app.module

import {DatePipe} from '@angular/common';
import {LogProvider, LogFileAppenderModule} from 'ionic-log-file-appender';


providers
---
File,
    DatePipe,
    LogProvider

Then on app.components
constructor( private log: LogProvider...

return log.init({
        /* Your config here */
      });


Just did ionic serve and was getting this error


Do I need to pass a config to the Init? 

Please provide an example

**Comment by hammadjamil** [comment]
> I integrated the plugin to my project. But when I am building it, it throws following error message:
> 
> `Uncaught Error: Can't resolve all parameters for LogProvider: ([object Object], [object Object], [object Object], ?). at syntaxError (vendor.js:108172) at CompileMetadataResolver._getDependenciesMetadata (vendor.js:124725) at CompileMetadataResolver._getTypeMetadata (vendor.js:124618) at CompileMetadataResolver._getInjectableTypeMetadata (vendor.js:124840) at CompileMetadataResolver.getProviderMetadata (vendor.js:124849) at vendor.js:124787 at Array.forEach (<anonymous>) at CompileMetadataResolver._getProvidersMetadata (vendor.js:124747) at CompileMetadataResolver.getNgModuleMetadata (vendor.js:124466) at JitCompiler._loadModules (vendor.js:131750)`
> 
> I am using Ionic Version 4.12.0.

I was also faced same error, but i am able to fix it by making following changes. Note I am using ionic 5

File to update : 
node_modules/ionic-log-file-appender/log.service.d.ts
node_modules/ionic-log-file-appender/fesm2015/ionic-log-file-appender.js

In both of above files I have made following changes: 

import { File } from '@ionic-native/file/ngx';
import { Platform } from '@ionic/angular';

I have update "from" part in above imports

Thats all.
