### ISSUE TITLE
change default log directory

### ISSUE THREAD

**Issue by dchiang** [SmartMoveSystems/ionicLogFileAppender#6]
Hi there,
According to the console output I was able to configure and generate logs by using your plugin but I can't access the files since they are being created in DataDirectoty which points to file:///data/user/0/com.mycompany.myapp/files/ and needs root permission.

Is there anyway to change the path (by configuration) so it works using externalDataDirectory (file:///storage/emulated/0/com.mycompany.myapp/files/) instead?

**Comment by y-a-n-n** [comment]
Hi there!

Currently, the logs are written to `cordova.file.dataDirectory`, and there is no way to change this through configuration.

If you'd like to submit a PR which adds an additional config parameter `baseDir` or similar, and defaults to this.file.dataDirectory if not specified, I'd be happy to review it.

For more info on the cordova file plugin:
https://github.com/apache/cordova-plugin-file#where-to-store-files

**Comment by y-a-n-n** [comment]
Hello again,

I have just released version 2.0.3 which incorporates this feature. Note that there are changes to the way the LogProvider should be incorporated into your project; please consult the README for details
