### ISSUE TITLE
Error: Can't resolve all parameters for LogProvider: (?, [object Object], [object Object])

### ISSUE THREAD

**Issue by ojpeters** [SmartMoveSystems/ionicLogFileAppender#7]
I am still getting the same error message: Error: Can't resolve all parameters for LogProvider: (?, [object Object], [object Object])

 I am having same issue.
Just added to my app.module

import {DatePipe} from '@angular/common';
import {LogProvider, LogFileAppenderModule} from 'ionic-log-file-appender';

providers
File,
DatePipe,
LogProvider

Then on app.components
constructor( private log: LogProvider...

return log.init({
/* Your config here */
});

Just did ionic serve and was getting this error

Do I need to pass a config to the Init?

Please provide an example
Also looks like npm install does not install the latest version

**Comment by y-a-n-n** [comment]
Hi there,

Please make sure you are importing the `File` provider from the correct place in your app.module, like so:

`import {File} from '@ionic-native/file';`

Also, I noted that you said you are using `ionic serve`, suggesting that your are running your app in the browser. Note that this package does not support logging to file in the browser, only on Android or iOS devices. 

You will still see your log messages printed to the browser console if you set `logToConsole: true` in your config, but no logs will be written to file unless you are running on a device.

**Comment by ojpeters** [comment]
I have spent lots of time to get this logging to work but no luck.

I did import the file as indicated and also tried  the ngx ie. import
{File} from '@ionic-native/file/*ngx*';
in the constructor, I injected file:File

but anytime I do any operation on the file object example
file.dataDirectory;
It fails at the stage where dataDirectory operation is done.

I have updated my ionic

I have also tested it on the device.
I am not sure if there is anything wrong with my environment.
Here is my :
"dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/android-full-screen": "^4.12.2",
    "@ionic-native/app-update": "^4.20.0",
    "@ionic-native/camera": "^4.12.2",
    "@ionic-native/camera-preview": "^4.12.2",
    "@ionic-native/core": "^5.1.0",
    "@ionic-native/file": "^5.8.0",
    "@ionic-native/http": "^4.14.0",
    "@ionic-native/network": "^4.20.0",
    "@ionic-native/screen-orientation": "^4.15.0",
    "@ionic-native/splash-screen": "~4.12.0",
    "@ionic-native/sqlite": "^4.17.0",
    "@ionic-native/status-bar": "~4.12.0",
    "@ionic/lab": "^1.0.9",
    "@ionic/storage": "2.1.3",
    "add": "^2.0.6",
    "angular2-signaturepad": "^2.8.0",
    "cordova": "^8.1.2",
    "cordova-android": "^7.1.1",
    "cordova-plugin-app-update": "2.0.2",
    "cordova-plugin-appversion": "1.0.0",
    "cordova-plugin-camera": "^4.0.3",
    "cordova-plugin-camera-preview": "^0.10.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-file": "6.0.1",
    "cordova-plugin-fullscreen": "^1.2.0",
    "cordova-plugin-ionic-keyboard": "^2.1.2",
    "cordova-plugin-ionic-webview": "^2.1.4",
    "cordova-plugin-network-information": "2.0.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-stetho-android": "0.0.1",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sqlite-storage": "2.5.1",
    "ionic-angular": "^3.9.2",
    "ionic-selectable": "^3.4.0"


I like your plugin and I am determined to use it.

Joseph Eze

**Comment by y-a-n-n** [comment]
The fact that you are successfully able to build and run on the device is a good sign.

What is the exact error message you are seeing when file operations are attempted in the dataDirectory?

If you want to see more detailed logs, I recommend setting `enableMetaLogging: true, logToConsole: true` in the config structure you pass in to the `log.init()` function. Then, a more detailed error message should appear in the console when debugging (i.e. in Chrome Dev tools if you are running on an Android device).

You may need to change the `baseDir` configuration parameter; your app may not have permission to write to the default directory.

**Comment by ojpeters** [comment]
The issue is that the app crashes on the device when it gets to load configuration. teh configuration requires that the data directory be specified. So I made a simple function to test of the native core file plugin is working. Here is the function:

testfileOp(){
  

  this.filestr.checkDir(this.filestr.dataDirectory, 'logs')
    .then(_ => console.log('Directory exists'))
    .catch(err =>
      console.log('Directory doesn\'t exist'));
 }

The same error  that occured when I run your script also happens here.

Here is the error message:
Property 'dataDirectory' does not exist on type 'File'

FYI, by app  does not start on the device  because of that

**Comment by y-a-n-n** [comment]
Interesting, but the fact that the `dataDirectory` property doesn't exist on the type `File` suggests misconfiguration of the `File` plugin, not this library. Your code snippet above doesn't actually invoke any code from this library at all, and in fact seems to come directly from here: https://ionicframework.com/docs/native/file

I recommend trying to investigate why your app is failing to properly use the File plugin. See if you can write some data to a file using your own code. If you can get that to work, I suspect you will be able to use this library as well.

**Comment by ojpeters** [comment]
In my app component, I used the following to init the function:

this.log.init({
        // Your config here /
        enableMetaLogging: false,
          logToConsole: false,
          logDateFormat: 'yyyy-MM-dd HH:mm:ss.SSS',
          fileDateFormat: 'yyyy-MM-dd_HH-mm-ss-SSS',
          fileMaxLines: 2000,
          fileMaxSize: 1000000,
          totalLogSize: 5000000,
          baseDir: null,
          logDir: 'logs',
          logPrefix: 'log',
          devMode: false
      }).catch(e => {
        console.log(e);
    });

Here is the error message


TypeError: Object(...) is not a function
    at File.get [as dataDirectory] (index.js:649)
    at logprovider.ts:56
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.js:4760)
    at t.invoke (polyfills.js:3)

**Comment by y-a-n-n** [comment]
@ojpeters Did you successfully create a file in your app manually using the `File` plugin as recommended?

**Comment by ojpeters** [comment]
No, I am not able yet to create a file. I am not sure what the issue is. Any advice?

**Comment by y-a-n-n** [comment]
Unfortunately your issue seems to be with the configuration of the File plugin in your project. Things I would recommend to try:

1. Make sure you have correctly added the plugin as well as the npm package to your project as per the "Installation" instructions here:
https://ionicframework.com/docs/native/file

2. Try version 4.17.0 of the file plugin. That is what one of my projects uses which successfully integrates this this library.

3. Have a look through the Ionic forums or https://github.com/ionic-team/ionic-native issues list to see if you can find similar issues with solutions. (A quick google led to this, which may be relevant: https://forum.ionicframework.com/t/error-typeerror-object-is-not-a-function/154554/6)

For now, I'm going to close this issue. If you get basic file operations working via the native plugin but still have issues with the file logger, please feel free to open a new issue.

**Comment by hammadjamil** [comment]
I was also faced same error, but i am able to fix it by making following changes. Note I am using ionic 5

File to update :
node_modules/ionic-log-file-appender/log.service.d.ts
node_modules/ionic-log-file-appender/fesm2015/ionic-log-file-appender.js

In both of above files I have made following changes:

import { File } from '@ionic-native/file/ngx';
import { Platform } from '@ionic/angular';

I have update "from" part in above imports

Thats all.

**Comment by y-a-n-n** [comment]
Thanks for the feedback, we'll look into updating the dependencies for this project
