### ISSUE TITLE
New log file is not generated when fileMaxLines is reached

### ISSUE THREAD

**Issue by BrunoJunior** [SmartMoveSystems/ionicLogFileAppender#8]
There is my ini conf : 
`this.logger.init({logDateFormat: 'dd-MM-yyyy HH:mm:ss.SSS', logToConsole: true, logPrefix: 'xlcomptage', fileDateFormat: 'yyyy-MM-dd'})`  

So, I use the default value `fileMaxLines: 2000`  

My file reached 4293 lines and no other file has been created ...

**Comment by y-a-n-n** [comment]
Just to be clear, in this context "lines" means "log entries, regardless of the length of each entry". So you're seeing > 2000 log entries being created in your file?

What version of the library are you using?

**Comment by BrunoJunior** [comment]
OK ...
So the config's label should be changed ^^ (fileMaxEntries)
I will be honnest, I don't want to count log entries by hand ;)
But, it's highly possible that some of my entries have more than 2 lines ...
I'll check that later

**Comment by y-a-n-n** [comment]
I appreciate that the config label could be named better, but I'm not going to make a breaking change to the api now that it's released. 

As a tip: if you use a log reader like glogg, counting the number of entries is trivial as it counts anything without a line break as a single line.
